### ISSUE TITLE
React - Axios

### ISSUE THREAD

**Issue by HenriqueFadoni** [KirankumarAmbati/I-can-not-REACT#15]
I could create a tutorial for React async code using Axios. It would be full of examples, and technical explanation.

**Comment by KirankumarAmbati** [comment]
Awesome ! @HenriqueFadoni

**Comment by KirankumarAmbati** [comment]
For now, I removed the assignment and made it open for pickup by any enthusiastic dev. 

@HenriqueFadoni , feel free to assign it to yourself if you would love to contribute. Thanks!

**Comment by maximilianoh** [comment]
Hi,
I have created some examples with classes and hooks, I just need to write. Can I take it?

**Comment by KirankumarAmbati** [comment]
Sure @maximilianoh. You can find the contributing guidelines in CONTRIBUTING.MD file. Thanks!

**Comment by KirankumarAmbati** [comment]
#41
