### ISSUE TITLE
JSX

### ISSUE THREAD

**Issue by andrewkoung** [KirankumarAmbati/I-can-not-REACT#17]
Hi! I'm completely new to open-source and thought this was a great place to start. If needed, I can make an article about JSX or any recommendation you have in mind?

**Comment by KirankumarAmbati** [comment]
Hi @andrewkoung,

Article on JSX actually helps beginners get an idea on how React looks. That helps a lot ! Please contribute. Happy to see that you are getting started to Open Source here. Happy coding n happy sharing ! :)

Will b waiting for your PR !

**Comment by KirankumarAmbati** [comment]
#19
