### ISSUE TITLE
Real world example

### ISSUE THREAD

**Issue by deshmanth** [KirankumarAmbati/I-can-not-REACT#20]
Building material on top of real world examples could be helpful for beginners

**Comment by KirankumarAmbati** [comment]
Sounds great !  Would love hear more. I'll be happy if you can write an article which can be referred fit future articles.will be waiting for your PR. Thanks a lot ! 😃

**Comment by anushkajj** [comment]
Hey! I would like to work on this.
(Beginner here!)

**Comment by KirankumarAmbati** [comment]
#53
