### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by KirankumarAmbati** [KirankumarAmbati/I-can-not-REACT#21]

**Comment by AjeaSmith** [comment]
Hi Kirankumar, just wondering if you started working on this issue? if not, I would love to help I have been using hooks a lot lately with my projects.

**Comment by KirankumarAmbati** [comment]
This issue is free to be picked up @AjeaSmith 😃

**Comment by AjeaSmith** [comment]
Thanks! Ill get started :)

**Comment by KirankumarAmbati** [comment]
Thanks for the contribution!
