### ISSUE TITLE
Functional or Class  - difference and when to use what  ?

### ISSUE THREAD

**Issue by KirankumarAmbati** [KirankumarAmbati/I-can-not-REACT#27]

**Comment by ddubrava** [comment]
We mentioned before that components defined as classes have some additional features. Local state is exactly that: a feature available only to classes.
- react docs

so if with state - use class. without state - function

**Comment by fgarcia-student** [comment]
Since React 16.8, the useState hook allows functional components the ability to retain local state across renders.

**Comment by KirankumarAmbati** [comment]
Good point ! @fgarcia-student Thanks for sharing that. Would you like to share an article on `hooks` ? That would help lot of people in getting started with hooks. Thank you!  🙂

**Comment by fgarcia-student** [comment]
Ofcourse! Sorry for my late reply.

Here are some resources to use in learning and exploring more about React Hooks:
[Official React Docs](https://reactjs.org/docs/hooks-intro.html)
[Dan Abramov talking about why they introduced the Hooks API](https://dev.to/dan_abramov/making-sense-of-react-hooks-2eib)
[Library of hooks you can use in your projects](https://nikgraf.github.io/react-hooks/)

**Comment by fgarcia-student** [comment]
@KirankumarAmbati would it be cool if I wrote an article on this? I can have it up by sunday morning and I'll link this site on my blog once I'm done updating it

**Comment by KirankumarAmbati** [comment]
It's totally cool. I would love to see a PR from you. Thanks! 🙂

**Comment by KirankumarAmbati** [comment]
Thanks @fgarcia-student for the PR! #33
