### ISSUE TITLE
Imperative vs Declarative programming

### ISSUE THREAD

**Issue by KirankumarAmbati** [KirankumarAmbati/I-can-not-REACT#28]

**Comment by Shrutihegde13** [comment]
Can I take this?

**Comment by KirankumarAmbati** [comment]
Sure @Shrutihegde13  👍

**Comment by Shrutihegde13** [comment]
I have no permission to push the changes.

**Comment by KirankumarAmbati** [comment]
@Shrutihegde13 You have to fork the repo, clone your repo, make changes in it and raise a PR. I can assist you if you need any help.

**Comment by Shrutihegde13** [comment]
Okay..

**Comment by KirankumarAmbati** [comment]
#31
