### ISSUE TITLE
Component Composition

### ISSUE THREAD

**Issue by KirankumarAmbati** [KirankumarAmbati/I-can-not-REACT#29]

**Comment by pleniloon** [comment]
Hi, can I help on this? I am new here so forgive my possible fuss.

**Comment by KirankumarAmbati** [comment]
Hi @pleniloon, 

This repo is mainly intended to bring out new Open Source Contributers. Feel free to contribute. Thanks!  🙂

**Comment by fosteman** [comment]
Hey, I composed a terse page on this topic. 
Can you guide me through adding a new page to your app?
Thanks

**Comment by KirankumarAmbati** [comment]
Sure @fosteman! 

Please create a folder in https://github.com/KirankumarAmbati/I-can-not-REACT/tree/master/content/blog with component-composition and create a index.md file and draft your content in it. Of you have any doubt still, you can either refer to any existing index.md file or drop a message here. Thanks!  🙂
