### ISSUE TITLE
Unidirectional Data Flow

### ISSUE THREAD

**Issue by KirankumarAmbati** [KirankumarAmbati/I-can-not-REACT#30]

**Comment by fosteman** [comment]
I can take it on, @KirankumarAmbati

**Comment by KirankumarAmbati** [comment]
Sure @fosteman! Thanks.

**Comment by KirankumarAmbati** [comment]
@fosteman, please can you add Front Matter for the other two articles ie. Flux and Component Composition. You can find it on top of index.md of any other article.

**Comment by fosteman** [comment]
@KirankumarAmbati  `package.json` doesn't contain `front-matter` [from here](https://www.npmjs.com/package/front-matter). 
Which package is used for purposes of parsing the meta-data instead?

**Comment by KirankumarAmbati** [comment]
I'm not quite sure @fosteman. I had used gatsby-starter-blog starter to generate this project and this functionality came with that. I didn't get deeper into it's functionality.
