### ISSUE TITLE
Importance of React

### ISSUE THREAD

**Issue by KirankumarAmbati** [KirankumarAmbati/I-can-not-REACT#5]
A brief article about why React became so popular ? What problem does it address ? etc.

**Comment by Pranav1999** [comment]
Where exactly should the article be included?

**Comment by KirankumarAmbati** [comment]
Hi Pranav !

You can create a file with name file-name.md and write the article in it.

**Comment by Pranav1999** [comment]
Ok.. I am not interested in doing this someone else can take up this issue.

**Comment by cellphone4ET** [comment]
Hey! Is this still up for grabs? How long would you like the article i.e. general word count

**Comment by KirankumarAmbati** [comment]
Yeah ! It is still up for grabs !!

Coming to the length of the article, I didn't have any definite length for an article. Please try to make it as detailed as possible, without loosing the gist. In case of any doubts, please feel free to reach out to me ! Thank you!

**Comment by cellphone4ET** [comment]
Ok awesome! I will get started on something
